import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Permission, RolePermission } from '@/database/entity';
import { generatedKey } from '../generatedKey';

@Injectable()
export class InitData {
  constructor(
    @InjectRepository(Permission, 'postgres') private readonly permissionRepository: Repository<Permission>,
    @InjectRepository(RolePermission, 'postgres') private readonly rolePermissionRepository: Repository<RolePermission>,
  ) {}

  async initPermissionData(allRoleIds: string[]) {
    const permissions = [
      {
        action: 'c',
        api_endpoint: 'api/permission',
        api_method: 'POST',
        api_type: '',
        group_permission: 'permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r',
        api_endpoint: 'api/permission',
        api_method: 'GET',
        api_type: '',
        group_permission: 'permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'u',
        api_endpoint: 'api/permission',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'd',
        api_endpoint: 'api/permission',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r_detail',
        api_endpoint: 'api/permission/',
        api_method: 'GET',
        api_type: '',
        group_permission: 'permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r_access_right',
        api_endpoint: '/api/permission/access-right',
        api_method: 'GET',
        api_type: '',
        group_permission: 'permission_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: 'api/role',
        api_method: 'POST',
        api_type: '',
        group_permission: 'role_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r',
        api_endpoint: 'api/role',
        api_method: 'GET',
        api_type: '',
        group_permission: 'role_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'u',
        api_endpoint: 'api/role',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'role_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'd',
        api_endpoint: 'api/role',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'role_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r_detail',
        api_endpoint: 'api/role/',
        api_method: 'GET',
        api_type: '',
        group_permission: 'role_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'c',
        api_endpoint: '/api/role-permission',
        api_method: 'POST',
        api_type: '',
        group_permission: 'role_permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r',
        api_endpoint: '/api/role-permission',
        api_method: 'GET',
        api_type: '',
        group_permission: 'role_permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'u',
        api_endpoint: '/api/role-permission',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'role_permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'd',
        api_endpoint: '/api/role-permission',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'role_permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r_detail',
        api_endpoint: '/api/role-permission/',
        api_method: 'GET',
        api_type: '',
        group_permission: 'role_permission_management',
        show_status: false,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'c_reset_password',
        api_endpoint: '/api/users/reset-password',
        api_method: 'POST',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/users',
        api_method: 'POST',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r',
        api_endpoint: '/api/users/report',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'r',
        api_endpoint: '/api/users/list',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'u',
        api_endpoint: '/api/users/update-user',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'd',
        api_endpoint: '/api/users/delete-user',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r_me',
        api_endpoint: '/api/users/me',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'r_network',
        api_endpoint: '/api/users/network',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'r_detail',
        api_endpoint: '/api/users/detail/',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'r_user_social',
        api_endpoint: '/api/users/user-social',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u_profile',
        api_endpoint: '/api/users/update-profile',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u_active',
        api_endpoint: '/api/users/active',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'user_management',
        show_status: true,
        roleIds: allRoleIds[0],
      },
      {
        action: 'u_change_pass',
        api_endpoint: '/api/users/change-password',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u_choose_language',
        api_endpoint: '/api/users/update-language',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'r_infor_kol',
        api_endpoint: '/api/users/info-kol',
        api_method: 'GET',
        api_type: 'social',
        group_permission: 'user_management',
        show_status: true,
        roleIds: allRoleIds[0],
      },
      {
        action: 'u_social_delete',
        api_endpoint: '/api/users/delete-social',
        api_method: 'DELETE',
        api_type: 'social',
        group_permission: 'user_management',
        show_status: true,
        roleIds: [allRoleIds[0], allRoleIds[1], allRoleIds[2]],
      },
      {
        action: 'u_social_user',
        api_endpoint: '/api/users/update-user-social',
        api_method: 'PUT',
        api_type: 'social',
        group_permission: 'user_management',
        show_status: true,
        roleIds: [allRoleIds[0]],
      },
      {
        action: 'r_export',
        api_endpoint: '/api/users/export',
        api_method: 'GET',
        api_type: '',
        group_permission: 'user_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/media/create-file',
        api_method: 'POST',
        api_type: '',
        group_permission: 'media_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'd',
        api_endpoint: '/api/media',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'media_management',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/language',
        api_method: 'POST',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: [allRoleIds[0], allRoleIds[1], allRoleIds[2]],
      },
      {
        action: 'c',
        api_endpoint: '/api/language',
        api_method: 'POST',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: [allRoleIds[0], allRoleIds[1], allRoleIds[2]],
      },
      {
        action: 'r',
        api_endpoint: '/api/language',
        api_method: 'GET',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'u',
        api_endpoint: '/api/language',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: [allRoleIds[0], allRoleIds[1], allRoleIds[2]],
      },
      {
        action: 'u_status',
        api_endpoint: '/api/language/update-status',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: [allRoleIds[0], allRoleIds[1], allRoleIds[2]],
      },
      {
        action: 'd',
        api_endpoint: '/api/language',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: [allRoleIds[0], allRoleIds[1], allRoleIds[2]],
      },
      {
        action: 'r_detail',
        api_endpoint: '/api/language/',
        api_method: 'GET',
        api_type: '',
        group_permission: 'language_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      // { // DUplicate
      //   action: 'r',
      //   api_endpoint: '/api/users/network',
      //   api_method: 'GET',
      //   api_type: '',
      //   group_permission: 'network_management',
      //   show_status: false,
      //   roleIds: allRoleIds[6],
      // },
      {
        action: 'r',
        api_endpoint: '/api/translations',
        api_method: 'GET',
        api_type: '',
        group_permission: 'translations_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'u',
        api_endpoint: '/api/translations',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'translations_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'd',
        api_endpoint: '/api/translations',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'translations_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/translations',
        api_method: 'POST',
        api_type: '',
        group_permission: 'translations_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'd_keywords',
        api_endpoint: '/api/translations/keywords',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'translations_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'u_keywords',
        api_endpoint: '/api/translations/keywords',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'translations_management',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'r',
        api_endpoint: '/api/setting/studio',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'r',
        api_endpoint: '/api/setting/department',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      { // office
        action: 'r',
        api_endpoint: '/api/setting/office',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      { 
        action: 'r',
        api_endpoint: '/api/setting/office/detail',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/setting/office',
        api_method: 'POST',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u',
        api_endpoint: '/api/setting/office/update',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'd',
        api_endpoint: '/api/setting/office/delete',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      { // exemption
        action: 'r',
        api_endpoint: '/api/setting/exemption',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      { 
        action: 'r',
        api_endpoint: '/api/setting/exemption/detail',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/setting/exemption',
        api_method: 'POST',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u',
        api_endpoint: '/api/setting/exemption/update',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'd',
        api_endpoint: '/api/setting/exemption/delete',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'r',
        api_endpoint: '/api/setting/revenues',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'r',
        api_endpoint: '/api/setting/system',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      { 
        action: 'r',
        api_endpoint: '/api/setting/revenue-install',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      { 
        action: 'r',
        api_endpoint: '/api/setting/revenue/detail',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/setting/create-revenue',
        api_method: 'POST',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u',
        api_endpoint: '/api/setting/revenue/update',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'd',
        api_endpoint: '/api/setting/revenue/delete',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      { 
        action: 'r',
        api_endpoint: '/api/setting/regime/detail',
        api_method: 'GET',
        api_type: '',
        group_permission: 'setting',
        show_status: true,
        roleIds: allRoleIds,
      },
      {
        action: 'c',
        api_endpoint: '/api/setting/create-regime',
        api_method: 'POST',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'u',
        api_endpoint: '/api/setting/regime/update',
        api_method: 'PUT',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'd',
        api_endpoint: '/api/setting/regime/delete',
        api_method: 'DELETE',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      },
      {
        action: 'c_import',
        api_endpoint: '/api/setting/import-exemption',
        api_method: 'POST',
        api_type: '',
        group_permission: 'setting',
        show_status: false,
        roleIds: allRoleIds,
      }
    ];

    for (const permission of permissions) {
      const existingPermission = await this.permissionRepository.findOneBy({
        action: permission.action,
        api_endpoint: permission.api_endpoint,
        api_method: permission.api_method,
      });

      if (!existingPermission) {
        const newPermission = this.permissionRepository.create({
          id: generatedKey.ref(32),
          action: permission.action,
          api_endpoint: permission.api_endpoint,
          api_method: permission.api_method,
          api_type: permission.api_type,
          group_permission: permission.group_permission,
          show_status: permission.show_status,
        });
        await this.permissionRepository.save(newPermission);

        const roleIds = Array.isArray(permission.roleIds) ? permission.roleIds : [permission.roleIds];
        const rolePermissions = roleIds.map((roleId) => ({
          id: generatedKey.ref(32),
          permission_id: newPermission.id,
          role_id: roleId,
        }));
        await this.rolePermissionRepository.save(rolePermissions);
      }
    }
  }
}
